// Generates src/shared.ts from the engine's single-source-of-truth browser JS
// (../src/shared/*.js). The Rust engine imports these same files via
// include_str! — regenerating here keeps the SDK's client-side heuristics
// byte-identical to the engine's, so detection can never drift.
//
// Run by `npm run gen` (part of build + test). Node-only, dev-time — never
// bundled into a Worker.
import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const here = dirname(fileURLToPath(import.meta.url));
const sharedDir = join(here, "..", "..", "src", "shared");

const read = (name) => readFileSync(join(sharedDir, name), "utf8");

// The files are self-contained IIFEs returning a JSON string. We embed them as
// template-literal-safe string constants (escape backticks + ${).
const escape = (s) => s.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${");

const humanNeeded = read("human-needed.js");
const axSnapshot = read("ax-snapshot.js");

const out = `// GENERATED by scripts/gen-shared.mjs — DO NOT EDIT.
// Single source of truth: ../../src/shared/*.js (also include_str!'d by the
// Rust engine). Regenerate with \`npm run gen\`.

/**
 * The in-page "a human must take over" probe, verbatim from the engine's
 * shared/human-needed.js. A self-contained IIFE that returns a JSON string
 * \`{kind}\` (\`password | captcha | cloudflare | oauth\`) or \`{}\`. Evaluate it in
 * the page (via browser_eval, when enabled) to run the SAME detection the engine
 * runs server-side — the SDK never re-implements these heuristics.
 */
export const HUMAN_NEEDED_JS = \`${escape(humanNeeded)}\`;

/**
 * The in-page accessibility-snapshot script, verbatim from the engine's
 * shared/ax-snapshot.js. Returns JSON \`{title,url,items:[…]}\`. Exposed for
 * parity/debugging; normal use goes through readPage()/snapshot() over the wire.
 */
export const AX_SNAPSHOT_JS = \`${escape(axSnapshot)}\`;
`;

writeFileSync(join(here, "..", "src", "shared.ts"), out);
console.error("gen-shared: wrote src/shared.ts");
